// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/v1/test.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_api_proto_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	mi := &file_api_proto_v1_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnaryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	IntervalMs    int32                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_v1_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_api_proto_v1_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BidirectionalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidirectionalRequest) Reset() {
	*x = BidirectionalRequest{}
	mi := &file_api_proto_v1_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalRequest) ProtoMessage() {}

func (x *BidirectionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalRequest.ProtoReflect.Descriptor instead.
func (*BidirectionalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{4}
}

func (x *BidirectionalRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BidirectionalRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type BidirectionalResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginalValue    int64                  `protobuf:"varint,1,opt,name=original_value,json=originalValue,proto3" json:"original_value,omitempty"`
	TransformedValue int64                  `protobuf:"varint,2,opt,name=transformed_value,json=transformedValue,proto3" json:"transformed_value,omitempty"`
	Operation        string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BidirectionalResponse) Reset() {
	*x = BidirectionalResponse{}
	mi := &file_api_proto_v1_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalResponse) ProtoMessage() {}

func (x *BidirectionalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalResponse.ProtoReflect.Descriptor instead.
func (*BidirectionalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_test_proto_rawDescGZIP(), []int{5}
}

func (x *BidirectionalResponse) GetOriginalValue() int64 {
	if x != nil {
		return x.OriginalValue
	}
	return 0
}

func (x *BidirectionalResponse) GetTransformedValue() int64 {
	if x != nil {
		return x.TransformedValue
	}
	return 0
}

func (x *BidirectionalResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *BidirectionalResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_v1_test_proto protoreflect.FileDescriptor

const file_api_proto_v1_test_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/test.proto\x12\x06api.v1\"(\n" +
	"\fUnaryRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"G\n" +
	"\rUnaryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"F\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x05R\n" +
	"intervalMs\"`\n" +
	"\x0eStreamResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"J\n" +
	"\x14BidirectionalRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"\xa7\x01\n" +
	"\x15BidirectionalResponse\x12%\n" +
	"\x0eoriginal_value\x18\x01 \x01(\x03R\roriginalValue\x12+\n" +
	"\x11transformed_value\x18\x02 \x01(\x03R\x10transformedValue\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xdc\x01\n" +
	"\vTestService\x124\n" +
	"\x05Unary\x12\x14.api.v1.UnaryRequest\x1a\x15.api.v1.UnaryResponse\x12?\n" +
	"\fServerStream\x12\x15.api.v1.StreamRequest\x1a\x16.api.v1.StreamResponse0\x01\x12V\n" +
	"\x13BidirectionalStream\x12\x1c.api.v1.BidirectionalRequest\x1a\x1d.api.v1.BidirectionalResponse(\x010\x01B8Z6github.com/vyrodovalexey/grpc-example/pkg/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_v1_test_proto_rawDescOnce sync.Once
	file_api_proto_v1_test_proto_rawDescData []byte
)

func file_api_proto_v1_test_proto_rawDescGZIP() []byte {
	file_api_proto_v1_test_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_test_proto_rawDesc), len(file_api_proto_v1_test_proto_rawDesc)))
	})
	return file_api_proto_v1_test_proto_rawDescData
}

var file_api_proto_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_test_proto_goTypes = []any{
	(*UnaryRequest)(nil),          // 0: api.v1.UnaryRequest
	(*UnaryResponse)(nil),         // 1: api.v1.UnaryResponse
	(*StreamRequest)(nil),         // 2: api.v1.StreamRequest
	(*StreamResponse)(nil),        // 3: api.v1.StreamResponse
	(*BidirectionalRequest)(nil),  // 4: api.v1.BidirectionalRequest
	(*BidirectionalResponse)(nil), // 5: api.v1.BidirectionalResponse
}
var file_api_proto_v1_test_proto_depIdxs = []int32{
	0, // 0: api.v1.TestService.Unary:input_type -> api.v1.UnaryRequest
	2, // 1: api.v1.TestService.ServerStream:input_type -> api.v1.StreamRequest
	4, // 2: api.v1.TestService.BidirectionalStream:input_type -> api.v1.BidirectionalRequest
	1, // 3: api.v1.TestService.Unary:output_type -> api.v1.UnaryResponse
	3, // 4: api.v1.TestService.ServerStream:output_type -> api.v1.StreamResponse
	5, // 5: api.v1.TestService.BidirectionalStream:output_type -> api.v1.BidirectionalResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_test_proto_init() }
func file_api_proto_v1_test_proto_init() {
	if File_api_proto_v1_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_test_proto_rawDesc), len(file_api_proto_v1_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_test_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_test_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_test_proto_msgTypes,
	}.Build()
	File_api_proto_v1_test_proto = out.File
	file_api_proto_v1_test_proto_goTypes = nil
	file_api_proto_v1_test_proto_depIdxs = nil
}
